app1/urls.py
from django.urls import path
from . import views

app_name='app1'

urlpatterns = [
    path('',views.index,name='index'),
     path('detail/<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls'))
]

app1/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

app1/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question,Choice
from django.urls import reverse


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    return render(request,'app1/index.html',{'latest_question_list':latest_question_list})

def detail(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request,'app1/detail.html',{'question':question})

def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request,'app1/detail.html',{'question':question,'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('app1:results', args=(question.id,)))


def results(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'app1/results.html',{'question':question})
    

app1/templates/app1/detail.html
<form action="{% url 'app1:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

app1/templates/app1/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list  %}
    <li><a href="/detail/{{question.id}}">{{question.question_text}}</a></li>    
    {% endfor %}
</ul>
{% else %}
<p>No Question Found..</p>
{% endif %}

app1/templates/app1/results.html
<h1>{{question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}} </li>
    {% endfor %}
</ul>
<a href="{%url 'app1:detail' question.id %}"><strong>Vote Again?</strong></a>